mvn clean package -Popenshift -DskipTests
docker build --tag=nowellpoint/console .
docker run -it \
-e AWS_REGION=$AWS_REGION \
-e AWS_ACCESS_KEY=$AWS_ACCESS_KEY \
-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
-e MONGO_CLIENT_URI=$MONGO_CLIENT_URI \
-e OKTA_API_KEY=$OKTA_API_KEY \
-e OKTA_ORG_URL=$OKTA_ORG_URL \
-e OKTA_CLIENT_ID=$OKTA_CLIENT_ID \
-e OKTA_CLIENT_SECRET=$OKTA_CLIENT_SECRET \
-e OKTA_AUTHORIZATION_SERVER=$OKTA_AUTHORIZATION_SERVER \
-e LOGGLY_API_ENDPOINT=$LOGGLY_API_ENDPOINT \
-e LOGGLY_API_KEY=$LOGGLY_API_KEY \
-e REDIS_HOST=$REDIS_HOST \
-e REDIS_ENCRYPTION_KEY=$REDIS_ENCRYPTION_KEY \
-e REDIS_PORT=$REDIS_PORT \
-e REDIS_PASSWORD=$REDIS_PASSWORD \
-e SENDGRID_API_KEY=$SENDGRID_API_KEY \
-e BRAINTREE_ENVIRONMENT=$BRAINTREE_ENVIRONMENT \
-e BRAINTREE_MERCHANT_ID=$BRAINTREE_MERCHANT_ID \
-e BRAINTREE_PUBLIC_KEY=$BRAINTREE_PUBLIC_KEY \
-e BRAINTREE_PRIVATE_KEY=$BRAINTREE_PRIVATE_KEY \
-p 8443:8443 nowellpoint/console:latest
