package com.nowellpoint.aws.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DoNotEncrypt;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@DynamoDBTable(tableName="Configurations")
@JsonIgnoreProperties(ignoreUnknown = true)
public class Setup {

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="Id")  
	private String id;
	
	@DynamoDBAttribute(attributeName="OrganizationId")  
	private String organizationId;
	
	@DynamoDBAttribute(attributeName="SalesforceUsername")
	private String salesforceUsername;
	
	@DynamoDBAttribute(attributeName="SalesforcePassword")
	private String salesforcePassword;
	
	@DynamoDBAttribute(attributeName="SalesforceSecurityToken")
	private String salesforceSecurityToken;
	
	public Setup() {
		
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DoNotEncrypt
	public String getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}
	
	public String getSalesforceUsername() {
		return salesforceUsername;
	}

	public void setSalesforceUsername(String salesforceUsername) {
		this.salesforceUsername = salesforceUsername;
	}

	public String getSalesforcePassword() {
		return salesforcePassword;
	}

	public void setSalesforcePassword(String salesforcePassword) {
		this.salesforcePassword = salesforcePassword;
	}

	public String getSalesforceSecurityToken() {
		return salesforceSecurityToken;
	}

	public void setSalesforceSecurityToken(String salesforceSecurityToken) {
		this.salesforceSecurityToken = salesforceSecurityToken;
	}

	public Setup withOrganizationId(String organizationId) {
		setOrganizationId(organizationId);
		return this;
	}
	
	public Setup withSalesforceUsername(String salesforceUsername) {
		setSalesforceUsername(salesforceUsername);
		return this;
	}
	
	public Setup withSalesforcePassword(String salesforcePassword) {
		setSalesforcePassword(salesforcePassword);
		return this;
	}
	
	public Setup withSalesforceSecurityToken(String salesforceSecurityToken) {
		setSalesforceSecurityToken(salesforceSecurityToken);
		return this;
	}
}