package com.nowellpoint.sdk.salesforce.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Profile extends SObject {
	
	private static final long serialVersionUID = 3004892024883616890L;

	public static final String QUERY = "Select "
			+ "CreatedById, "
			+ "CreatedDate, "
			+ "Description, "
			+ "Id, "
			+ "LastModifiedById, "
			+ "LastModifiedDate, "
			+ "LastReferencedDate, "
			+ "LastViewedDate, "
			+ "Name, "
			+ "PermissionsAccessCMC, "
			+ "PermissionsActivateContract, "
			+ "PermissionsActivateOrder, "
			+ "PermissionsAddDirectMessageMembers, "
			+ "PermissionsAllowLightningLogin, "
			+ "PermissionsAllowUniversalSearch, "
			+ "PermissionsAllowViewEditConvertedLeads, "
			+ "PermissionsAllowViewKnowledge, "
			+ "PermissionsApexRestServices, "
			+ "PermissionsApiEnabled, "
			+ "PermissionsAssignPermissionSets, "
			+ "PermissionsAssignTopics, "
			+ "PermissionsAuthorApex, "
			+ "PermissionsBulkApiHardDelete, "
			+ "PermissionsBulkMacrosAllowed, "
			+ "PermissionsCampaignInfluence2, "
			+ "PermissionsCanApproveFeedPost, "
			+ "PermissionsCanInsertFeedSystemFields, "
			+ "PermissionsCanUseNewDashboardBuilder, "
			+ "PermissionsCanVerifyComment, "
			+ "PermissionsChangeDashboardColors, "
			+ "PermissionsChatterComposeUiCodesnippet, "
			+ "PermissionsChatterEditOwnPost, "
			+ "PermissionsChatterEditOwnRecordPost, "
			+ "PermissionsChatterInternalUser, "
			+ "PermissionsChatterInviteExternalUsers, "
			+ "PermissionsChatterOwnGroups, "
			+ "PermissionsConfigCustomRecs, "
			+ "PermissionsConnectOrgToEnvironmentHub, "
			+ "PermissionsContentAdministrator, "
			+ "PermissionsContentWorkspaces, "
			+ "PermissionsConvertLeads, "
			+ "PermissionsCreateCustomizeFilters, "
			+ "PermissionsCreateMultiforce, "
			+ "PermissionsCreateReductionOrder, "
			+ "PermissionsCreateTopics, "
			+ "PermissionsCreateWorkspaces, "
			+ "PermissionsCustomizeApplication, "
			+ "PermissionsCustomMobileAppsAccess, "
			+ "PermissionsCustomSidebarOnAllPages, "
			+ "PermissionsDataExport, "
			+ "PermissionsDelegatedTwoFactor, "
			+ "PermissionsDeleteActivatedContract, "
			+ "PermissionsDeleteTopics, "
			+ "PermissionsEditActivatedOrders, "
			+ "PermissionsEditBrandTemplates, "
			+ "PermissionsEditCaseComments, "
			+ "PermissionsEditEvent, "
			+ "PermissionsEditHtmlTemplates, "
			+ "PermissionsEditKnowledge, "
			+ "PermissionsEditOppLineItemUnitPrice, "
			+ "PermissionsEditPublicDocuments, "
			+ "PermissionsEditPublicFilters, "
			+ "PermissionsEditPublicTemplates, "
			+ "PermissionsEditReadonlyFields, "
			+ "PermissionsEditReports, "
			+ "PermissionsEditTask, "
			+ "PermissionsEditTopics, "
			+ "PermissionsEmailAdministration, "
			+ "PermissionsEmailMass, "
			+ "PermissionsEmailSingle, "
			+ "PermissionsEmailTemplateManagement, "
			+ "PermissionsEnableCommunityAppLauncher, "
			+ "PermissionsEnableNotifications, "
			+ "PermissionsExportReport,"
			+ "PermissionsFeedPinning, "
			+ "PermissionsFlowUFLRequired, "
			+ "PermissionsForceTwoFactor, "
			+ "PermissionsGovernNetworks, "
			+ "PermissionsHideReadByList, "
			+ "PermissionsIdentityConnect, "
			+ "PermissionsIdentityEnabled, "
			+ "PermissionsImportCustomObjects, "
			+ "PermissionsImportLeads, "
			+ "PermissionsImportPersonal, "
			+ "PermissionsInstallMultiforce, "
			+ "PermissionsIotUser, "
			+ "PermissionsLightningConsoleAllowedForUser, "
			+ "PermissionsLightningExperienceUser, "
			+ "PermissionsListEmailSend, "
			+ "PermissionsManageAnalyticSnapshots, "
			+ "PermissionsManageAuthProviders, "
			+ "PermissionsManageBusinessHourHolidays, "
			+ "PermissionsManageCallCenters, "
			+ "PermissionsManageCases, "
			+ "PermissionsManageCategories, "
			+ "PermissionsManageCertificates, "
			+ "PermissionsManageChatterMessages, "
			+ "PermissionsManageContentPermissions, "
			+ "PermissionsManageContentProperties, "
			+ "PermissionsManageContentTypes, "
			+ "PermissionsManageCssUsers, "
			+ "PermissionsManageCustomPermissions, "
			+ "PermissionsManageCustomReportTypes, "
			+ "PermissionsManageDashboards, "
			+ "PermissionsManageDataCategories, "
			+ "PermissionsManageDataIntegrations, "
			+ "PermissionsManageDynamicDashboards, "
			+ "PermissionsManageEmailClientConfig, "
			+ "PermissionsManageExchangeConfig, "
			+ "PermissionsManageHealthCheck, "
			+ "PermissionsManageInteraction, "
			+ "PermissionsManageInternalUsers, "
			+ "PermissionsManageIpAddresses, "
			+ "PermissionsManageKnowledge, "
			+ "PermissionsManageKnowledgeImportExport, "
			+ "PermissionsManageLeads, "
			+ "PermissionsManageLoginAccessPolicies, "
			+ "PermissionsManageMobile, "
			+ "PermissionsManageNetworks, "
			+ "PermissionsManagePasswordPolicies, "
			+ "PermissionsManageProfilesPermissionsets, "
			+ "PermissionsManagePvtRptsAndDashbds, "
			+ "PermissionsManageRemoteAccess, "
			+ "PermissionsManageRoles, "
			+ "PermissionsManageSearchPromotionRules, "
			+ "PermissionsManageSelfService, "
			+ "PermissionsManageSessionPermissionSets, "
			+ "PermissionsManageSharing, "
			+ "PermissionsManageSolutions, "
			+ "PermissionsManageSurveys, "
			+ "PermissionsManageSynonyms, "
			+ "PermissionsManageTwoFactor, "
			+ "PermissionsManageUnlistedGroups, "
			+ "PermissionsManageUsers, "
			+ "PermissionsMergeTopics, "
			+ "PermissionsModerateChatter, "
			+ "PermissionsModerateNetworkUsers, "
			+ "PermissionsModifyAllData, "
			+ "PermissionsModifySecureAgents, "
			+ "PermissionsNewReportBuilder, "
			+ "PermissionsPackaging2, "
			+ "PermissionsPasswordNeverExpires, "
			+ "PermissionsPreventClassicExperience, "
			+ "PermissionsPublishMultiforce, "
			+ "PermissionsRemoveDirectMessageMembers, "
			+ "PermissionsResetPasswords, "
			+ "PermissionsRunFlow, "
			+ "PermissionsRunReports, "
			+ "PermissionsSalesConsole, "
			+ "PermissionsScheduleReports, "
			+ "PermissionsSelectFilesFromSalesforce, "
			+ "PermissionsSendAnnouncementEmails, "
			+ "PermissionsSendSitRequests, "
			+ "PermissionsShareInternalArticles, "
			+ "PermissionsShowCompanyNameAsUserBadge, "
			+ "PermissionsSolutionImport, "
			+ "PermissionsSubmitMacrosAllowed, "
			+ "PermissionsSubscribeToLightningDashboards, "
			+ "PermissionsSubscribeToLightningReports, "
			+ "PermissionsTransferAnyCase, "
			+ "PermissionsTransferAnyEntity, "
			+ "PermissionsTransferAnyLead, "
			+ "PermissionsTwoFactorApi, "
			+ "PermissionsUseTeamReassignWizards, "
			+ "PermissionsUseWebLink, "
			+ "PermissionsViewAllActivities, "
			+ "PermissionsViewAllData, "
			+ "PermissionsViewAllUsers, "
			+ "PermissionsViewContent, "
			+ "PermissionsViewDataAssessment, "
			+ "PermissionsViewDataCategories, "
			+ "PermissionsViewEncryptedData, "
			+ "PermissionsViewEventLogFiles, "
			+ "PermissionsViewHealthCheck, "
			+ "PermissionsViewHelpLink, "
			+ "PermissionsViewMyTeamsDashboards, "
			+ "PermissionsViewRoles, "
			+ "PermissionsViewSetup, "
			+ "UserLicenseId, "
			+ "UserType "
			+ "From Profile";
	
	@JsonProperty("Name")
	private String name;
	
	@JsonProperty("Description")
	private String description;
	
	@JsonProperty("UserType")
	private String userType;
	
	public Profile() {
		
	}

	public String getName() {
		return name;
	}

	public String getDescription() {
		return description;
	}

	public String getUserType() {
		return userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}
}