FROM java:openjdk-8-jdk
EXPOSE 9090
ADD /target/nowellpoint-aws-api-0.0.2-SNAPSHOT-swarm.jar nowellpoint-aws-api-0.0.2-SNAPSHOT-swarm.jar
ENTRYPOINT ["java","-jar","nowellpoint-aws-api-0.0.2-SNAPSHOT-swarm.jar"]
