package com.nowellpoint.api.util;

public class EnvUtil {
	
	public static enum Variable {
		LOGGLY_API_KEY,
		LOGGLY_API_ENDPOINT,
		MONGO_CLIENT_URI,
		SALESFORCE_CLIENT_ID,
		SALESFORCE_CLIENT_SECRET,
		SALESFORCE_AUTHORIZE_URI,
		SALESFORCE_TOKEN_URI,
		SALESFORCE_REFRESH_URI,
		SALESFORCE_REVOKE_URI,
		SALESFORCE_USERNAME,
		SALESFORCE_PASSWORD,
		SALESFORCE_SECURITY_TOKEN,
		SALESFORCE_REDIRECT_URI,
		SALESFORCE_API_VERSION,
		OKTA_API_KEY,
		OKTA_ORG_URL,
		OKTA_GROUP_ID,
		OKTA_CLIENT_ID,
		OKTA_CLIENT_SECRET,
		OKTA_AUTHORIZATION_SERVER,
		SENDGRID_API_KEY,
		REDIS_PASSWORD,
		REDIS_HOST,
		REDIS_PORT,
		DEFAULT_SUBJECT,
		CACHE_DATA_ENCRYPTION_KEY,
		BRAINTREE_ENVIRONMENT,
		BRAINTREE_MERCHANT_ID,
		BRAINTREE_PUBLIC_KEY,
		BRAINTREE_PRIVATE_KEY,
		VERIFY_EMAIL_REDIRECT ,
		CLOUDFRONT_HOSTNAME,
		APPLICATION_HOSTNAME,
		API_HOSTNAME
	}
	
	public static String getValue(Variable variable) {
		return System.getenv(variable.name());
	}
}