package com.nowellpoint.braintree.webhook;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DoNotEncrypt;

@DynamoDBTable(tableName="PAYMENT_GATEWAY_NOTIFICATIONS")
public class PaymentGatewayNotification {
	
	public enum Status {
		RECEIVED,
		PROCESSED
	}
	
	private String id;
	
	private String environment;
	
	private String merchantId;
	
	private String publicKey;
	
	private String privateKey;
	
	private String subscriptionId;
	
	private String status;
	
	private String webhookNotification;
	
	public PaymentGatewayNotification() {
		
	}

	@DynamoDBHashKey(attributeName="Id")
	@DynamoDBAutoGeneratedKey
	public String getId() { 
		return id; 
	}

	public void setId(String id) { 
		this.id = id; 
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="Environment")  
	public String getEnvironment() { 
		return environment; 
	}

	public void setEnvironment(String environment) { 
		this.environment = environment; 
	}

	@DynamoDBAttribute(attributeName="MerchantId")  
	public String getMerchantId() {
		return merchantId;
	}

	public void setMerchantId(String merchantId) {
		this.merchantId = merchantId;
	}

	@DynamoDBAttribute(attributeName="PublicKey")  
	public String getPublicKey() {
		return publicKey;
	}

	public void setPublicKey(String publicKey) {
		this.publicKey = publicKey;
	}

	@DynamoDBAttribute(attributeName="PrivateKey")  
	public String getPrivateKey() {
		return privateKey;
	}

	public void setPrivateKey(String privateKey) {
		this.privateKey = privateKey;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="SubscriptionId")  
	public String getSubscriptionId() {
		return subscriptionId;
	}

	public void setSubscriptionId(String subscriptionId) {
		this.subscriptionId = subscriptionId;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="Status")  
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@DoNotEncrypt
	@DynamoDBAttribute(attributeName="WebhookNotification") 
	public String getWebhookNotification() {
		return webhookNotification;
	}

	public void setWebhookNotification(String webhookNotification) {
		this.webhookNotification = webhookNotification;
	}
	
	public PaymentGatewayNotification environment(String environment) {
		setEnvironment(environment);
		return this;
	}
	
	public PaymentGatewayNotification merchantId(String merchantId) {
		setMerchantId(merchantId);
		return this;
	}
	
	public PaymentGatewayNotification privateKey(String privateKey) {
		setPrivateKey(privateKey);
		return this;
	}
	
	public PaymentGatewayNotification publicKey(String publicKey) {
		setPublicKey(publicKey);
		return this;
	}
	
	public PaymentGatewayNotification subscriptionId(String subscriptionId) {
		setSubscriptionId(subscriptionId);
		return this;
	}
	
	public PaymentGatewayNotification webhookNotification(String webhookNotification) {
		setWebhookNotification(webhookNotification);
		return this;
	}
	
	public PaymentGatewayNotification status(String status) {
		setStatus(status);
		return this;
	}
}