package com.nowellpoint.aws.data.dynamodb;

import java.io.Serializable;
import java.time.Instant;
import java.util.Date;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DoNotEncrypt;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;

@DynamoDBTable(tableName="Events")
public class Event implements Serializable {
	
	/**
	 * 
	 */
	
	private static final long serialVersionUID = 6661489942230811436L;

	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName="Id")  
	private String id;
	
	@DynamoDBRangeKey(attributeName="SubjectId")  
	private String subject;
	
	@DynamoDBAttribute(attributeName="EventStatus")  
	private String eventStatus;
	
	@DynamoDBAttribute(attributeName="EventDate")  
	private Date eventDate;
	
	@DynamoDBAttribute(attributeName="StartTime")
	private Long startTime;
	
	@DynamoDBAttribute(attributeName="ProcessedDate")  
	private Date processedDate;
	
	@DynamoDBAttribute(attributeName="Payload")
	private String payload;
	
	@DynamoDBAttribute(attributeName="TargetId")
	private String targetId;
	
	@DynamoDBAttribute(attributeName="TargetId")
	private String type;
	
	@DynamoDBAttribute(attributeName="ExecutionTime")
	private Long executionTime;
	
	@DynamoDBAttribute(attributeName="ErrorMessage")
	private String errorMessage;
	
	@DynamoDBAttribute(attributeName="EventSource")
	private String eventSource;
	
	@DynamoDBAttribute(attributeName="EventAction")
	private String eventAction;
	
	@DynamoDBAttribute(attributeName="PropertyStore")
	private String propertyStore;
	
	@DynamoDBAttribute(attributeName="ParentEventId")
	private String parentEventId;
	
	
	public Event() {
		
	}
	
	public Event(String type, String subject, String eventSource, EventAction eventAction, String payload, String propertyStore, String parentEventId) {
		setType(type);
		setEventStatus(EventStatus.NEW.name());
		setSubject(subject);
		setEventSource(eventSource);
		setEventAction(eventAction.name());
		setPayload(payload);
		setEventDate(Date.from(Instant.now()));
		setPropertyStore(propertyStore);
		setParentEventId(parentEventId);
	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@DoNotEncrypt
	public String getEventStatus() {
		return eventStatus;
	}

	public void setEventStatus(String eventStatus) {
		this.eventStatus = eventStatus;
	}
	
	@DoNotEncrypt
	public Date getEventDate() {
		return eventDate;
	}

	public void setEventDate(Date eventDate) {
		this.eventDate = eventDate;
	}
	
	@DoNotEncrypt
	public String getType() {
		return type;
	}
	
	public void setType(String type) {
		this.type = type;
	}

	@DoNotEncrypt
	public Date getProcessedDate() {
		return processedDate;
	}

	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}
	
	@DoNotEncrypt
	public Long getStartTime() {
		return startTime;
	}
	
	public void setStartTime(Long startTime) {
		this.startTime = startTime;
	}

	@DoNotEncrypt
	public String getSubject() {
		return subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getPayload() {
		return payload;
	}

	public void setPayload(String payload) {
		this.payload = payload;
	}

	@DoNotEncrypt
	public String getTargetId() {
		return targetId;
	}

	public void setTargetId(String targetId) {
		this.targetId = targetId;
	}

	@DoNotEncrypt
	public Long getExecutionTime() {
		return executionTime;
	}

	public void setExecutionTime(Long executionTime) {
		this.executionTime = executionTime;
	}

	@DoNotEncrypt
	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}
	
	@DoNotEncrypt
	public String getEventSource() {
		return eventSource;
	}
	
	public void setEventAction(String eventAction) {
		this.eventAction = eventAction;
	}
	
	@DoNotEncrypt
	public String getEventAction() {
		return eventAction;
	}

	public void setEventSource(String eventSource) {
		this.eventSource = eventSource;
	}

	@DoNotEncrypt
	public String getPropertyStore() {
		return propertyStore;
	}

	public void setPropertyStore(String propertyStore) {
		this.propertyStore = propertyStore;
	}

	@DoNotEncrypt
	public String getParentEventId() {
		return parentEventId;
	}

	public void setParentEventId(String parentEventId) {
		this.parentEventId = parentEventId;
	}
}