package com.nowellpoint.sforce.model;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.encryption.DoNotEncrypt;

@DynamoDBTable(tableName="MetadataBackupRequests")
public class MetadataBackupRequest {
	
	@DynamoDBHashKey(attributeName="OrganizationId")  
	private String organizationId;
	
	@DynamoDBAutoGeneratedKey
	@DynamoDBRangeKey(attributeName="Key")
	private String key;
	
	@DynamoDBAttribute(attributeName="SessionId")
	private String sessionId;
	
	@DynamoDBAttribute(attributeName="SobjectsUrl")
	private String sobjectsUrl;
	
	@DynamoDBAttribute(attributeName="BucketName")
	private String bucketName;
	
	@DynamoDBAttribute(attributeName="AwsAccessKey")
	private String awsAccessKey;
	
	@DynamoDBAttribute(attributeName="AwsSecretAccessKey")
	private String awsSecretAccessKey;
	
	@DynamoDBAttribute(attributeName="ProcessDuration")  
	private Long processDuration;
	
	@DynamoDBAttribute(attributeName="ProcessedDate")  
	private Date processedDate;
	
	@DynamoDBAttribute(attributeName="Status")
	private String status;
	
	@DynamoDBAttribute(attributeName="ErrorMessage")
	private String errorMessage;

	public MetadataBackupRequest() {
		
	}

	public String getOrganizationId() {
		return organizationId;
	}

	public void setOrganizationId(String organizationId) {
		this.organizationId = organizationId;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	@DoNotEncrypt
	public String getSobjectsUrl() {
		return sobjectsUrl;
	}
	
	public void setSobjectsUrl(String sobjectsUrl) {
		this.sobjectsUrl = sobjectsUrl;
	}

	@DoNotEncrypt
	public String getBucketName() {
		return bucketName;
	}

	public void setBucketName(String bucketName) {
		this.bucketName = bucketName;
	}

	public String getAwsAccessKey() {
		return awsAccessKey;
	}

	public void setAwsAccessKey(String awsAccessKey) {
		this.awsAccessKey = awsAccessKey;
	}

	public String getAwsSecretAccessKey() {
		return awsSecretAccessKey;
	}

	public void setAwsSecretAccessKey(String awsSecretAccessKey) {
		this.awsSecretAccessKey = awsSecretAccessKey;
	}

	public String getSessionId() {
		return sessionId;
	}

	public void setSessionId(String sessionId) {
		this.sessionId = sessionId;
	}
	
	@DoNotEncrypt
	public Long getProcessDuration() {
		return processDuration;
	}

	public void setProcessDuration(Long processDuration) {
		this.processDuration = processDuration;
	}

	@DoNotEncrypt
	public Date getProcessedDate() {
		return processedDate;
	}

	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}

	@DoNotEncrypt
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@DoNotEncrypt
	public String getErrorMessage() {
		return errorMessage;
	}

	public void setErrorMessage(String errorMessage) {
		this.errorMessage = errorMessage;
	}
}